// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_INCLUDED_message_2eproto
#define PROTOBUF_INCLUDED_message_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_message_2eproto 

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_message_2eproto
namespace message {
class StartReq;
class StartReqDefaultTypeInternal;
extern StartReqDefaultTypeInternal _StartReq_default_instance_;
}  // namespace message
namespace google {
namespace protobuf {
template<> ::message::StartReq* Arena::CreateMaybeMessage<::message::StartReq>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace message {

// ===================================================================

class StartReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:message.StartReq) */ {
 public:
  StartReq();
  virtual ~StartReq();

  StartReq(const StartReq& from);

  inline StartReq& operator=(const StartReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StartReq(StartReq&& from) noexcept
    : StartReq() {
    *this = ::std::move(from);
  }

  inline StartReq& operator=(StartReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StartReq* internal_default_instance() {
    return reinterpret_cast<const StartReq*>(
               &_StartReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(StartReq* other);
  friend void swap(StartReq& a, StartReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StartReq* New() const final {
    return CreateMaybeMessage<StartReq>(NULL);
  }

  StartReq* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StartReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StartReq& from);
  void MergeFrom(const StartReq& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StartReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 local_ip = 1;
  bool has_local_ip() const;
  void clear_local_ip();
  static const int kLocalIpFieldNumber = 1;
  ::google::protobuf::uint32 local_ip() const;
  void set_local_ip(::google::protobuf::uint32 value);

  // required uint32 local_port = 2;
  bool has_local_port() const;
  void clear_local_port();
  static const int kLocalPortFieldNumber = 2;
  ::google::protobuf::uint32 local_port() const;
  void set_local_port(::google::protobuf::uint32 value);

  // required uint32 remote_ip = 3;
  bool has_remote_ip() const;
  void clear_remote_ip();
  static const int kRemoteIpFieldNumber = 3;
  ::google::protobuf::uint32 remote_ip() const;
  void set_remote_ip(::google::protobuf::uint32 value);

  // required uint32 remote_port = 4;
  bool has_remote_port() const;
  void clear_remote_port();
  static const int kRemotePortFieldNumber = 4;
  ::google::protobuf::uint32 remote_port() const;
  void set_remote_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:message.StartReq)
 private:
  void set_has_local_ip();
  void clear_has_local_ip();
  void set_has_local_port();
  void clear_has_local_port();
  void set_has_remote_ip();
  void clear_has_remote_ip();
  void set_has_remote_port();
  void clear_has_remote_port();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 local_ip_;
  ::google::protobuf::uint32 local_port_;
  ::google::protobuf::uint32 remote_ip_;
  ::google::protobuf::uint32 remote_port_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StartReq

// required uint32 local_ip = 1;
inline bool StartReq::has_local_ip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StartReq::set_has_local_ip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StartReq::clear_has_local_ip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StartReq::clear_local_ip() {
  local_ip_ = 0u;
  clear_has_local_ip();
}
inline ::google::protobuf::uint32 StartReq::local_ip() const {
  // @@protoc_insertion_point(field_get:message.StartReq.local_ip)
  return local_ip_;
}
inline void StartReq::set_local_ip(::google::protobuf::uint32 value) {
  set_has_local_ip();
  local_ip_ = value;
  // @@protoc_insertion_point(field_set:message.StartReq.local_ip)
}

// required uint32 local_port = 2;
inline bool StartReq::has_local_port() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StartReq::set_has_local_port() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StartReq::clear_has_local_port() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StartReq::clear_local_port() {
  local_port_ = 0u;
  clear_has_local_port();
}
inline ::google::protobuf::uint32 StartReq::local_port() const {
  // @@protoc_insertion_point(field_get:message.StartReq.local_port)
  return local_port_;
}
inline void StartReq::set_local_port(::google::protobuf::uint32 value) {
  set_has_local_port();
  local_port_ = value;
  // @@protoc_insertion_point(field_set:message.StartReq.local_port)
}

// required uint32 remote_ip = 3;
inline bool StartReq::has_remote_ip() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StartReq::set_has_remote_ip() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StartReq::clear_has_remote_ip() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StartReq::clear_remote_ip() {
  remote_ip_ = 0u;
  clear_has_remote_ip();
}
inline ::google::protobuf::uint32 StartReq::remote_ip() const {
  // @@protoc_insertion_point(field_get:message.StartReq.remote_ip)
  return remote_ip_;
}
inline void StartReq::set_remote_ip(::google::protobuf::uint32 value) {
  set_has_remote_ip();
  remote_ip_ = value;
  // @@protoc_insertion_point(field_set:message.StartReq.remote_ip)
}

// required uint32 remote_port = 4;
inline bool StartReq::has_remote_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void StartReq::set_has_remote_port() {
  _has_bits_[0] |= 0x00000008u;
}
inline void StartReq::clear_has_remote_port() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void StartReq::clear_remote_port() {
  remote_port_ = 0u;
  clear_has_remote_port();
}
inline ::google::protobuf::uint32 StartReq::remote_port() const {
  // @@protoc_insertion_point(field_get:message.StartReq.remote_port)
  return remote_port_;
}
inline void StartReq::set_remote_port(::google::protobuf::uint32 value) {
  set_has_remote_port();
  remote_port_ = value;
  // @@protoc_insertion_point(field_set:message.StartReq.remote_port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_message_2eproto
